version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo-data:
